package org.venus.openapi;

import org.venus.cache.ValueWrapper;

import java.util.List;

/**
 * Interface defining the operations for handling OpenAPI entities.
 *
 * This interface provides methods to retrieve and manipulate OpenAPI entities,
 * which represent URL mapping information.
 */
public interface IOpenapiService {
    /**
     * Retrieves an ValueWrapper based on the provided short code.
     *
     * @param encode the unique identifier code for the URL mapping, which is a
     *               62-bit encoded string (consisting of [0-9], [a-z], [A-Z])
     *               provided by the user or generated by the system.
     * @return the ValueWrapper object corresponding to the provided code,
     *         or null if no entity is found with the given code.
     */
    ValueWrapper get(String encode);

    /**
     * Retrieves a list of all OpenAPI entities.
     *
     * @return a list of {@link ValueWrapper} representing all URL mappings.
     */
    List<ValueWrapper> lists();

    /**
     * Redirects the original URL to its corresponding ValueWrapper.
     *
     * @param original the original URL to be redirected
     * @return the ValueWrapper that contains the redirect information for the original URL
     */
    ValueWrapper redirect(String original);

}
